package com.example.oasystem_1_0.dao;

import com.example.oasystem_1_0.domain.po.Process;
import com.example.oasystem_1_0.domain.po.ProcessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    int countByExample(ProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    int deleteByExample(ProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    int insert(Process record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    int insertSelective(Process record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    List<Process> selectByExample(ProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    Process selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") Process record, @Param("example") ProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    int updateByExample(@Param("record") Process record, @Param("example") ProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    int updateByPrimaryKeySelective(Process record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    int updateByPrimaryKey(Process record);
}