package com.example.oasystem_1_0.domain.po;

import java.util.Date;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    private Long id;

    @Override
    public String toString() {
        return "Item{" +
                "id=" + id +
                ", itemTime='" + itemTime + '\'' +
                ", conductor='" + conductor + '\'' +
                ", carLicence='" + carLicence + '\'' +
                ", carType='" + carType + '\'' +
                ", itemNumber='" + itemNumber + '\'' +
                ", driver='" + driver + '\'' +
                ", telephone='" + telephone + '\'' +
                ", userId=" + userId +
                ", weight='" + weight + '\'' +
                ", project='" + project + '\'' +
                ", others='" + others + '\'' +
                ", gmtCreate=" + gmtCreate +
                ", gmtModified=" + gmtModified +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_time
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    private String itemTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.conductor
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    private String conductor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.car_linense
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    private String carLicence;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.car_type
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    private String carType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_number
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    private String itemNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.driver
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    private String driver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.telephone
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.user_id
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.weight
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    private String weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.project
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    private String project;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.others
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    private String others;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.gmt_create
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.gmt_modified
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_time
     *
     * @return the value of item.item_time
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public String getItemTime() {
        return itemTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_time
     *
     * @param itemTime the value for item.item_time
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public void setItemTime(String itemTime) {
        this.itemTime = itemTime == null ? null : itemTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.conductor
     *
     * @return the value of item.conductor
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public String getConductor() {
        return conductor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.conductor
     *
     * @param conductor the value for item.conductor
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public void setConductor(String conductor) {
        this.conductor = conductor == null ? null : conductor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.car_linense
     *
     * @return the value of item.car_linense
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public String getCarLicence() {
        return carLicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.car_linense
     *
     * @param carLicence the value for item.car_linense
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public void setCarLicence(String carLicence) {
        this.carLicence = carLicence == null ? null : carLicence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.car_type
     *
     * @return the value of item.car_type
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.car_type
     *
     * @param carType the value for item.car_type
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_number
     *
     * @return the value of item.item_number
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public String getItemNumber() {
        return itemNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_number
     *
     * @param itemNumber the value for item.item_number
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public void setItemNumber(String itemNumber) {
        this.itemNumber = itemNumber == null ? null : itemNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.driver
     *
     * @return the value of item.driver
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public String getDriver() {
        return driver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.driver
     *
     * @param driver the value for item.driver
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public void setDriver(String driver) {
        this.driver = driver == null ? null : driver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.telephone
     *
     * @return the value of item.telephone
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.telephone
     *
     * @param telephone the value for item.telephone
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.user_id
     *
     * @return the value of item.user_id
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.user_id
     *
     * @param userId the value for item.user_id
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.weight
     *
     * @return the value of item.weight
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.weight
     *
     * @param weight the value for item.weight
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.project
     *
     * @return the value of item.project
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.project
     *
     * @param project the value for item.project
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.others
     *
     * @return the value of item.others
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.others
     *
     * @param others the value for item.others
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.gmt_create
     *
     * @return the value of item.gmt_create
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.gmt_create
     *
     * @param gmtCreate the value for item.gmt_create
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.gmt_modified
     *
     * @return the value of item.gmt_modified
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.gmt_modified
     *
     * @param gmtModified the value for item.gmt_modified
     *
     * @mbggenerated Wed Apr 18 11:41:04 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}