package com.example.oasystem_1_0.domain.po;

import java.util.Date;

public class Process {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.id
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    private Long id;

    @Override
    public String toString() {
        return "Process{" +
                "id=" + id +
                ", isLoading=" + isLoading +
                ", arrTime='" + arrTime + '\'' +
                ", depTime='" + depTime + '\'' +
                ", itemId=" + itemId +
                ", gmtCreate=" + gmtCreate +
                ", gmtModified=" + gmtModified +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.is_loading
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    private Byte isLoading;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.arr_time
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    private String arrTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.dep_time
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    private String depTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.item_id
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.gmt_create
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.gmt_modified
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.id
     *
     * @return the value of process.id
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.id
     *
     * @param id the value for process.id
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.is_loading
     *
     * @return the value of process.is_loading
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    public Byte getIsLoading() {
        return isLoading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.is_loading
     *
     * @param isLoading the value for process.is_loading
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    public void setIsLoading(Byte isLoading) {
        this.isLoading = isLoading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.arr_time
     *
     * @return the value of process.arr_time
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    public String getArrTime() {
        return arrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.arr_time
     *
     * @param arrTime the value for process.arr_time
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    public void setArrTime(String arrTime) {
        this.arrTime = arrTime == null ? null : arrTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.dep_time
     *
     * @return the value of process.dep_time
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    public String getDepTime() {
        return depTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.dep_time
     *
     * @param depTime the value for process.dep_time
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    public void setDepTime(String depTime) {
        this.depTime = depTime == null ? null : depTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.item_id
     *
     * @return the value of process.item_id
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.item_id
     *
     * @param itemId the value for process.item_id
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.gmt_create
     *
     * @return the value of process.gmt_create
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.gmt_create
     *
     * @param gmtCreate the value for process.gmt_create
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.gmt_modified
     *
     * @return the value of process.gmt_modified
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.gmt_modified
     *
     * @param gmtModified the value for process.gmt_modified
     *
     * @mbggenerated Wed Apr 18 15:54:15 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}